"""Optional MNE-BIDS-Pipeline backend shim."""

from __future__ import annotations

import subprocess
from pathlib import Path

import mne
import numpy as np

from ..m0_intake.bids_convert import convert_subject_to_bids
from ..m0_intake.naming import rest_ds
from ..m2_preprocess.filter import apply_band, apply_notch_and_resample
from ..m3_epoching.rest import make_pseudo_epochs


def _subject_label(subject: str) -> str:
    return subject.removeprefix("sub-")


def _bids_deriv_root(cfg) -> Path:
    custom = getattr(cfg.preprocess, "bids_pipeline_deriv_root", "")
    if custom:
        return Path(custom).expanduser()
    return cfg.derivatives_root / "mne-bids-pipeline"


def _render_config_py(subject: str, cfg, out_path: Path) -> None:
    subj = _subject_label(subject)
    bids_root = Path(cfg.data_root).expanduser().resolve()
    deriv_root = _bids_deriv_root(cfg).resolve()
    deriv_root.mkdir(parents=True, exist_ok=True)
    content = f"""# Auto-generated by mous_pipeline.m2_preprocess.bids_pipeline_backend
bids_root = r\"{bids_root}\"
deriv_root = r\"{deriv_root}\"
subjects = [\"{subj}\"]

task = \"auditory\"
ch_types = [\"meg\"]

l_freq = 1.0
h_freq = None
raw_resample_sfreq = {float(cfg.preprocess.resample_hz)}
spatial_filter = \"ica\"
ica_n_components = {int(cfg.preprocess.ica_n_components)}

epochs_tmin = {float(cfg.epoching.tmin)}
epochs_tmax = {float(cfg.epoching.tmax)}
baseline = ({float(cfg.epoching.baseline[0])}, {float(cfg.epoching.baseline[1])})
conditions = [\"ZINNEN\", \"WOORDEN\"]

use_template_mri = \"fsaverage\"
spacing = \"oct6\"
"""
    out_path.write_text(content)


def _run_pipeline(config_py: Path, *, steps: str) -> None:
    cmd = ["mne_bids_pipeline", f"--config={config_py}", f"--steps={steps}"]
    subprocess.run(cmd, check=True, capture_output=True, text=True)


def _find_task_epochs(deriv_root: Path, subject: str) -> Path | None:
    subj = _subject_label(subject)
    patterns = [
        f"**/sub-{subj}/**/*task-auditory*epo.fif",
        f"**/sub-{subj}/**/*auditory*epo.fif",
        f"**/sub-{subj}/**/*epo.fif",
    ]
    for pat in patterns:
        matches = sorted(deriv_root.glob(pat))
        if matches:
            return matches[0]
    return None


def run_preprocessing(subject: str, cfg) -> tuple[mne.Epochs, mne.Epochs]:
    """
    Run mne_bids_pipeline preprocessing steps and read back task epochs.

    Rest pseudo-epochs are still derived from local rest CTF recording.
    """
    convert_subject_to_bids(subject, cfg)
    deriv_root = _bids_deriv_root(cfg)
    cfg_dir = deriv_root / "generated_configs"
    cfg_dir.mkdir(parents=True, exist_ok=True)
    config_py = cfg_dir / f"sub-{_subject_label(subject)}_mne_bids_config.py"
    _render_config_py(subject, cfg, config_py)
    _run_pipeline(config_py, steps="preprocessing")

    task_epochs_path = _find_task_epochs(deriv_root, subject)
    if task_epochs_path is None:
        raise FileNotFoundError(f"Could not find MNE-BIDS-Pipeline epochs for sub-{_subject_label(subject)} in {deriv_root}")
    task_epochs = mne.read_epochs(str(task_epochs_path), preload=True, verbose="ERROR")

    rest_raw = mne.io.read_raw_ctf(
        str(rest_ds(_subject_label(subject), cfg.data_root)),
        preload=True,
        system_clock="truncate",
        verbose="WARNING",
    )
    rest_raw.apply_gradient_compensation(3)
    rest_raw = apply_notch_and_resample(rest_raw, cfg)
    rest_raw = apply_band(rest_raw, 13, 30)
    epoch_len = cfg.epoching.tmax - cfg.epoching.tmin
    rest_epochs = make_pseudo_epochs(rest_raw, epoch_len)
    return task_epochs, rest_epochs


def run_source(subject: str, cfg) -> dict:
    """Run mne_bids_pipeline source step and report discovered STC outputs."""
    deriv_root = _bids_deriv_root(cfg)
    cfg_dir = deriv_root / "generated_configs"
    cfg_dir.mkdir(parents=True, exist_ok=True)
    config_py = cfg_dir / f"sub-{_subject_label(subject)}_mne_bids_config.py"
    _render_config_py(subject, cfg, config_py)
    _run_pipeline(config_py, steps="source")
    subj = _subject_label(subject)
    stc_files = sorted(deriv_root.glob(f"**/sub-{subj}/**/*stc*"))
    return {
        "source_backend": "mne_bids_pipeline",
        "source_stc_files_found": int(len(stc_files)),
        "source_stc_example": str(stc_files[0]) if stc_files else "",
        "source_stc_lengths_mean": float(np.mean([f.stat().st_size for f in stc_files])) if stc_files else 0.0,
    }
